services:
  gateway:
    container_name: ignition
    image: inductiveautomation/ignition:latest
    ports:
      - 9088:8088
      - 9043:8043
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bratislava
      - ACCEPT_IGNITION_EULA=Y
      - GATEWAY_ADMIN_USERNAME=${GATEWAY_ADMIN_USERNAME}
      - GATEWAY_ADMIN_PASSWORD=${GATEWAY_ADMIN_PASSWORD}
      - IGNITION_LICENSE_KEY=${IGNITION_LICENSE_KEY}
      - IGNITION_ACTIVATION_TOKEN=${IGNITION_ACTIVATION_TOKEN}
      - IGNITION_EDITION=${IGNITION_EDITION} #standard, edge, or maker
    volumes:
      - ./projects:/usr/local/bin/ignition/data/projects
    command:
     - wrapper.java.maxmemory=2048
    network_mode: bridge
    restart: unless-stopped