services:
  service-name:
    container_name: name
    image: image/image:latest
    ports:
      - 0:0
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bratislava
    volumes:
      - /volume:/volume
    env_file: .env
    runtime: nvidia
    devices:
      - device:device
    device_cgroup_rules:
      - rule
    privileged: true
    user: 0:0
    command:
      - command
    entrypoint: entrypoint
    pid: host
    cap_add:
      - cap_add
    sysctls:
      - sysctls
    links:
      - links
    depends_on:
      - depends_on
    network_mode: bridge / host
    networks:
      - network
    hostname: name
    restart: unless-stopped

networks:
  network-name:
    name: network-name
    driver: bridge

volumes:
  volume-name:
    name: volume-name
    driver: local
  volume-name:
    name: volume-name
    driver: local
    driver_opts:
      type: nfs
      o: addr=${IP},rw,nolock,soft,nfsvers=4
      device: ${DEVICE}