services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bratislava
    volumes:
      - grafana:/var/lib/grafana
    network_mode: bridge
    restart: unless-stopped

volumes:
  grafana:
    external: true