services:
  # Common
  protainer-agent:
    container_name: protainer-agent
    image: portainer/agent:latest
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - dns
    restart: unless-stopped

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bratislava
      - WATCHTOWER_MONITOR_ONLY=false
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 6 0 * * 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dns
    restart: unless-stopped

  # Specific
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80
    environment:
      - TZ=Europe/Bratislava
      - FTLCONF_webserver_api_password=${PASSWORD}
      - FTLCONF_dns_listeningMode=all
    volumes:
      - './pihole:/etc/pihole'
    cap_add:
      - SYS_NICE
    networks:
      - dns
    hostname: PiHole
    restart: unless-stopped

networks:
  dns:
    name: dns
    driver: bridge