services:
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - PGID=1000
      - PUID=1000
      - VERSION=docker
      - TZ=Europe/Bratislava
    volumes:
      - ./config:/config
      - movies:/movies
    network_mode: bridge
    # network_mode: host
    restart: unless-stopped

volumes:
  movies:
    external: true