services:
  npm:
    container_name: npm
    image: jc21/nginx-proxy-manager:latest
    ports:
      - 80:80
      - 81:81
      - 443:443
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Eurepe/Bratislava
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    network_mode: bridge
    restart: unless-stopped