services:
  transmission:
    container_name: transmission
    image: lscr.io/linuxserver/transmission:latest
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bratislava
    volumes:
      - ./config:/config
      - downloads:/downloads
      - watch:/watch
    network_mode: bridge
    restart: unless-stopped

volumes:
  downloads:
    external: true
  watch:
    external: true
  