services:
  grav:
    container_name: grav
    image: lscr.io/linuxserver/grav:latest
    ports:
      - 9080:80
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bratislava
    volumes:
      - ./grav/config:/config
    networks:
      - cloud
    restart: unless-stopped

  minecraft:
    container_name: minecraft
    image: itzg/minecraft-server:latest
    ports:
      - 25565:25565
    environment:
      - EULA=TRUE
    volumes:
      - ./minecraft/data:/data
    networks:
      - cloud
    restart: unless-stopped

networks:
  cloud:
    name: cloud
    driver: bridge