services:
  node-red:
    container_name: node-red
    image: nodered/node-red:latest
    ports:
      - 1880:1880
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bratislava
    volumes:
      - nodered:/data
    network_mode: bridge
    restart: unless-stopped

volumes:
  nodered:
    external: true