volumes:
  # Portainer
  portainer:
    name: portainer
    driver: local
  # Media
  downloads:
    name: downloads
    driver: local
    driver_opts:
      type: cifs
      device: ${DOWNLOADS}
      o: username=${USERNAME},password=${PASSWORD},uid=1000,gid=1000
  movies:
    name: movies
    driver: local
    driver_opts:
      type: cifs
      device: ${MOVIES}
      o: username=${USERNAME},password=${PASSWORD},uid=1000,gid=1000
  watch:
    name: watch
    driver: local
    driver_opts:
      type: cifs
      device: ${WATCH}
      o: username=${USERNAME},password=${PASSWORD},uid=1000,gid=1000