volumes:
  # DB
  nextcloud-db:
    name: nextcloud_db
    driver: local
    driver_opts:
      type: cifs
      device: ${NEXTCLOUD_DB}
      o: username=${USERNAME},password=${PASSWORD},uid=1000,gid=1000
  # Duplicati
  backups:
    name: backups
    driver: local
    driver_opts:
      type: cifs
      device: ${BACKUPS}
      o: username=${USERNAME},password=${PASSWORD},uid=1000,gid=1000
  # Grafana
  grafana:
    name: grafana
    driver: local
  # Media
  downloads:
    name: downloads
    driver: local
    driver_opts:
      type: cifs
      device: ${DOWNLOADS}
      o: username=${USERNAME},password=${PASSWORD},uid=1000,gid=1000
  movies:
    name: movies
    driver: local
    driver_opts:
      type: cifs
      device: ${MOVIES}
      o: username=${USERNAME},password=${PASSWORD},uid=1000,gid=1000
  watch:
    name: watch
    driver: local
    driver_opts:
      type: cifs
      device: ${WATCH}
      o: username=${USERNAME},password=${PASSWORD},uid=1000,gid=1000
  # Octoprint
  octoprint:
    name: octoprint
    driver: local
  # Portainer
  portainer:
    name: portainer
    driver: local
  # Prometheus
  prometheus:
    name: prometheus
    driver: local