volumes:
  # DB

  # Duplicati
  backups:
    name: backups
    driver: local
    driver_opts:
      type: cifs
      device: ${BACKUPS}
      o: username=${USERNAME},password=${PASSWORD},uid=1000,gid=1000
  # Media
  downloads:
    name: downloads
    driver: local
    driver_opts:
      type: cifs
      device: ${DOWNLOADS}
      o: username=${USERNAME},password=${PASSWORD},uid=1000,gid=1000
  movies:
    name: movies
    driver: local
    driver_opts:
      type: cifs
      device: ${MOVIES}
      o: username=${USERNAME},password=${PASSWORD},uid=1000,gid=1000
  watch:
    name: watch
    driver: local
    driver_opts:
      type: cifs
      device: ${WATCH}
      o: username=${USERNAME},password=${PASSWORD},uid=1000,gid=1000
  # Octoprint
  octoprint:
    name: octoprint
    driver: local
  # Portainer
  portainer:
    name: portainer
    driver: local
  # PrusaSlicer
  prusaslicer:
    name: prusaslicer
    driver: local
    driver_opts:
      type: cifs
      device: ${PRUSASLICER}
      o: username=${USERNAME},password=${PASSWORD},uid=1000,gid=1000