services:
  service-name:
    container_name: name
    image: image/image:latest
    ports:
      - 0:0
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bratislava
    volumes:
      - /volume:/volume
    env_file: .env
    runtime: nvidia
    devices:
      - device:device
    privileged: true
    command:
      - command
    pid: host
    cap_add:
      - cap_add
    sysctls:
      - sysctls
    links:
      - links
    depends_on:
      - depends_on
    network_mode: bridge / host
    networks:
      - network
    restart: unless-stopped

volumes:
  volume-name:
    external: true