services:
  service-name:
    container_name: name
    image: image/image:latest
    ports:
      - 0:0
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Eurepe/Bratislava
    volumes:
      - /volume:/volume
    devices:
      - device:device
    command:
      - command
    cap_add:
      - cap_add
    sysctls:
      - sysctls
    network_mode: bridge
    restart: unless-stopped

volumes:
  volume-name:
    external: true