services:
  service-name:
    container_name: wireguard
    image: linuxserver/wireguard:latest
    ports:
      - 51820:51820/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bratislava
      - SERVERURL=${SERVERURL}
      - SERVERPORT=51820
      - PEERS=1
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    network_mode: bridge
    restart: unless-stopped