services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - monitoring
    restart: unless-stopped

  prometheus:
    container_name: prometheus
    image: docker.io/prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus:/prometheus
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    depends_on:
      - node_exporter
      - cadvisor
      - nvidia_smi_exporter
    networks:
      - monitoring
    restart: unless-stopped

  # System metrics
  node_exporter:
    container_name: node_exporter
    image: quay.io/prometheus/node-exporter:latest
    ports:
      - 9100:9100
    volumes:
      - /:/host:ro,rslave
    command: "--path.rootfs=/host"
    pid: host
    networks:
      - monitoring
    restart: unless-stopped

  # Container metrics
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /run:/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    networks:
      - monitoring
    restart: unless-stopped

  # Nvidia GPU metrics - comment if not using Nvidia GPUs
  nvidia_smi_exporter:
    container_name: nvidia_smi_exporter
    image: utkuozdemir/nvidia_gpu_exporter:latest
    ports:
      - 9835:9835
    volumes:
      - /usr/lib/x86_64-linux-gnu/libnvidia-ml.so:/usr/lib/x86_64-linux-gnu/libnvidia-ml.so
      - /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
      - /usr/bin/nvidia-smi:/usr/bin/nvidia-smi
    devices:
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia0:/dev/nvidia0
    networks:
      - monitoring
    restart: unless-stopped

networks:
  monitoring:
    name: monitoring
    driver: bridge

volumes:
  grafana:
    driver: local
  prometheus:
    driver: local