- hosts: 'SRV_DNS_BKP'
  become: yes
  tasks:
    - name: Update packages
      apt:
        update_cache: yes
        upgrade: "yes"
        autoremove: True

    - name: Set timezone
      command: timedatectl set-timezone Europe/Bratislava

    - name: Set hostname
      hostname:
        name: "SRV-DNS-BKP"

    - name: Download and run AdGuardHome install script
      shell: |
        curl -s -S -L https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh -s -- -v
      args:
        executable: /bin/bash

    - name: Start AdGuardHome service
      shell: /opt/AdGuardHome/AdGuardHome -s start