- hosts: 'SRV_Collection, PC_Desktop'
  become: yes
  tasks:
    - name: Update packages
      apt:
        update_cache: yes
        upgrade: "yes"
        autoremove: True

    - name: Reboot
      reboot:
        reboot_timeout: 120