services:
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bratislava
    volumes:
      - ./config:/config
      - downloads:/downloads
      - movies:/movies
    network_mode: bridge
    restart: unless-stopped

volumes:
  downloads:
    external: true
  movies:
    external: true