services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 83:80
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bratislava
      - WEBPASSWORD=${WEBPASSWORD}
    volumes:
      - ./pihole:/etc/pihole
      - ./dnsmasq.d:/etc/dnsmasq.d
    network_mode: bridge
    restart: unless-stopped