services:
  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    ports:
      - 6767:6767
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bratislava
    volumes:
      - ./bazarr/config:/config
      - movies:/movies
    networks:
      - media
    restart: unless-stopped

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    ports:
      - 9696:9696
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bratislava
    volumes:
      - ./prowlarr/config:/config
    networks:
      - media
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bratislava
    volumes:
      - ./radarr/config:/config
      - downloads:/downloads
      - movies:/movies
    networks:
      - media
    restart: unless-stopped

  transmission:
    container_name: transmission
    image: lscr.io/linuxserver/transmission:latest
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bratislava
    volumes:
      - ./transmission/config:/config
      - downloads:/downloads
      - watch:/watch
    networks:
      - media
    restart: unless-stopped

  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Bratislava
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
      - NVIDIA_VISIBLE_DEVICES=all # comment out if you don't have a nvidia card
      - NVIDIA_DRIVER_CAPABILITIES=all # comment out if you don't have a nvidia card
    volumes:
      - ./plex/config:/config
      - movies:/movies
    devices:
      # - /dev/dri:/dev/dri # uncomment out if you don't have a nvidia card
    runtime: nvidia # comment out if you don't have a nvidia card
    network_mode: host
    restart: unless-stopped

networks:
  media:
    name: media
    driver: bridge

volumes:
  downloads:
    name: downloads
    driver: local
    driver_opts:
      type: cifs
      device: ${DOWNLOADS}
      o: username=${USERNAME},password=${PASSWORD},uid=1000,gid=1000
  movies:
    name: movies
    driver: local
    driver_opts:
      type: cifs
      device: ${MOVIES}
      o: username=${USERNAME},password=${PASSWORD},uid=1000,gid=1000
  watch:
    name: watch
    driver: local
    driver_opts:
      type: cifs
      device: ${WATCH}
      o: username=${USERNAME},password=${PASSWORD},uid=1000,gid=1000