services:
  mariadb:
    container_name: mariadb
    image: lscr.io/linuxserver/mariadb:latest
    ports:
      - 3306:3306
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bratislava
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./config:/config
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - nextcloud_db:/config/databases/nextcloud
    network_mode: bridge
    restart: unless-stopped

volumes:
  nextcloud_db:
    external: true