services:
  mariadb:
    container_name: mariadb
    image: lscr.io/linuxserver/mariadb:latest
    ports:
      - 3306:3306
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bratislava
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./config:/config
      - ./data:/config/databases/data
    network_mode: bridge
    restart: unless-stopped