global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['ip:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['ip:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['ip:8080']