services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bratislava
    volumes:
      - ./config.yaml/:/etc/prometheus/prometheus.yaml:ro
      - prometheus:/prometheus
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    network_mode: bridge
    restart: unless-stopped

volumes:
  prometheus:
    external: true