services:
  grav:
    container_name: grav
    image: lscr.io/linuxserver/grav:latest
    ports:
      - 83:80
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bratislava
    volumes:
      - ./config:/config
    network_mode: bridge
    restart: unless-stopped