services:
  db:
    container_name: mysql
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - ./databases:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password
    network_mode: bridge
    restart: unless-stopped