services:
  nextcloud:
    container_name: nextcloud
    image: lscr.io/linuxserver/nextcloud:latest
    ports:
      - 8443:443
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bratislava
    volumes:
      - ./config:/config
      - nextcloud:/data
    network_mode: bridge
    restart: unless-stopped

volumes:
  nextcloud:
    external: true