services:
  octoprint:
    container_name: octoprint
    image: octoprint/octoprint:latest
    ports:
      - 80:80
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bratislava
    volumes:
      - octoprint:/octoprint
    devices:
     - /dev/ttyACM0:/dev/ttyACM0
    network_mode: bridge
    restart: unless-stopped

volumes:
  octoprint:
    external: true