services:
  octoprint:
    container_name: octoprint
    image: octoprint/octoprint:latest
    ports:
      - 9000:80
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bratislava
    volumes:
     - uploads:/octoprint/octoprint/uploads
     - plugins:/octoprint/plugins
    devices:
     - /dev/ttyACM0:/dev/ttyACM0
    network_mode: bridge
    restart: unless-stopped

volumes:
  uploads:
    external: true
  plugins:
    external: true