services:
  freecad:
    container_name: freecad
    image: lscr.io/linuxserver/freecad:latest
    ports:
      - 3000:3000
      - 3001:3001
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bratislava
    volumes:
      - ./config:/config
      - printing:/models
    network_mode: bridge
    restart: unless-stopped

volumes:
  printing:
    external: true