services:
  duplicati:
    container_name: duplicati
    image: lscr.io/linuxserver/duplicati:latest
    ports:
      - 8200:8200
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Eurepe/Bratislava
    volumes:
      - ./config:/config
      - backups:/backups
      - ./../../../HoneyLab:/source
    network_mode: bridge
    restart: unless-stopped

volumes:
  backups:
    external: true