services:
  duckdns:
    container_name: duckdns
    image: lscr.io/linuxserver/duckdns:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bratislava
      - SUBDOMAINS=${SUBDOMAINS}
      - TOKEN=${TOKEN}
      - UPDATE_IP=ipv4
      - LOG_FILE=true
    volumes:
      - ./config:/config
    network_mode: bridge
    restart: unless-stopped